# name: Docker Image CI

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:

#   build_image:

#     runs-on: ubuntu-latest
#     steps:
#     - name: Docker Login
#       uses: docker/login-action@v3.2.0
#       with:
#         username: ${{ secrets.USER_DOCKER }} # optional
#         password: ${{ secrets.PASSWORD_DOCKER }}
#     - name: Checkout the code
#       uses: actions/checkout@v4
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag devsu:$(date +%s) --build-arg DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }} --build-arg DATABASE_NAME=${{ secrets.DATABASE_NAME }}

name: Publish Docker image

permissions:
  id-token: write
  contents: read
  attestations: write
  packages: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.USER_DOCKER }}
          password: ${{ secrets.PASSWORD_DOCKER }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: rolo96/devsu
          tags: $(echo $GITHUB_SHA | cut -c1-6)

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
            DATABASE_NAME=${{ secrets.DATABASE_NAME }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: rolo96/devsu
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
        env:
          DOCKER_USERNAME: ${{ secrets.USER_DOCKER }}
          DOCKER_PASSWORD: ${{ secrets.PASSWORD_DOCKER }}