name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Docker Login
  # You may pin to the exact commit or the version.
  # uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
      uses: docker/login-action@v3.2.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        # registry: # optional
        # Username used to log against the Docker registry
        username: rolo96 # optional
        # Password or personal access token used to log against the Docker registry
        password: MP7R$ooc5 # optional
        # Specifies whether the given registry is ECR (auto, true or false)
        #ecr: # optional, default is auto
        # Log out from the Docker registry at the end of a job
        #logout: # optional, default is true
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag devsu:$(date +%s) --build-arg DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }} --build-arg DATABASE_NAME=${{ secrets.DATABASE_NAME }}

    
          